name: Mike's Blog
markdown: redcarpet
pygments: true
safe: true
exclude: ['node_modules', 'bootstrap', 'jquery']
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]