# Site settings
title: Blog de Mike
name: Blog de Mike
header-img: img/home-bg.jpg
email: miguelerm@gmail.com
copyright_name: Mike
description: "Blog con artículos de programación web en .Net C# y JavaScript principalmente, posiblemente tambien algo de SQL"
baseurl: ""
url: "http://miguelerm.github.io"
repository: miguelerm/miguelerm.github.io

author:
  name     : 'Miguel Román'
  email    : miguelerm@gmail.com
  url      : https://plus.google.com/+MiguelEduardoRomanMartinez/about
  facebook : miguelerm
  twitter  : miguelerm
  github   : miguelerm

disqus_shortname: "miguelerm"
google_analytics: UA-40921433-1

excerpt_separator: <!-- more -->

compress_html:
  comments: ["<!-- ", " -->"]

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules","Gruntfile.js","package.json","README.md", "gulpfile.js", "css/main.css", "js/miguelerm.js", 'bootstrap', 'jquery', '*.less', '*.js', '*.log', '*.bat']
  
gems: [jekyll-paginate, jekyll-feed]
